**Question 1:
A group of people from different parts of Ranchi visited ‘Universal Studio’, Singapore and they enjoyed various fun events.
- The first event was ‘Roller Coaster’ for which the ticket price was 44 dollars for male, 38 dollars for females and 21 dollars for kids. They spent a total of 1412 dollars for this event.
- Second event was ‘4D Max Cinema’ for which ticket prices were 32 dollars, 28 dollars and 15 dollars respectively. They spent 1024 dollars for this event.
- Finally they had a ‘cable car’ trip for which the ticket prices were 24 dollars, 20 dollars and 10 dollars respectively. They spent 728 dollars for the cable car trip.



In [1]:
import numpy as np

# Coefficients of the system of equations
A = np.array([[44, 38, 21],
              [32, 28, 15],
              [24, 20, 10]])

# Right-hand side of the equations (total money spent in each event)
B = np.array([1412, 1024, 728])

# Solving the system of linear equations
solution = np.linalg.solve(A, B)

# Extracting the number of males, females, and kids
males, females, kids = solution

print(f"Number of males: {int(males)}")
print(f"Number of females: {int(females)}")
print(f"Number of kids: {int(kids)}")


Number of males: 12
Number of females: 9
Number of kids: 24


###
**Question 2:** Write a python script to
Construct two numpy 3D arrays A1 and A2 of any shape set by the user at run time and the elements are randomly generated by the system. Perform the following steps
1) Construct an array by selecting all the elements of the first array (A1) that are divisible by 5
2) Construct another array by selecting all the elements of the second array (A2) that are divisible by 4
3) Join 1 and 2 to form a single dimensional array and construct the largest possible square matrix from it


In [2]:
import numpy as np

# Get user input for the shape of the arrays
shape_A1 = tuple(map(int, input("Enter the shape of A1 (e.g., 2 3 4): ").split()))
shape_A2 = tuple(map(int, input("Enter the shape of A2 (e.g., 2 3 4): ").split()))

# Construct two random 3D arrays
A1 = np.random.randint(1, 100, size=shape_A1)
A2 = np.random.randint(1, 100, size=shape_A2)

print("Array A1:")
print(A1)
print("\nArray A2:")
print(A2)

# Select elements divisible by 5 from A1
divisible_by_5_A1 = A1[A1 % 5 == 0]

# Select elements divisible by 4 from A2
divisible_by_4_A2 = A2[A2 % 4 == 0]

# Join the two arrays
joined_array = np.concatenate((divisible_by_5_A1, divisible_by_4_A2))

# Construct the largest possible square matrix
matrix_size = int(np.floor(np.sqrt(len(joined_array))))  # Largest square size
square_matrix = joined_array[:matrix_size * matrix_size].reshape(matrix_size, matrix_size)

print("\nJoined Array (divisible by 5 from A1 and divisible by 4 from A2):")
print(joined_array)

print("\nLargest Possible Square Matrix:")
print(square_matrix)


Enter the shape of A1 (e.g., 2 3 4):  2 3 4
Enter the shape of A2 (e.g., 2 3 4):  2 3 4


Array A1:
[[[31 32 21 90]
  [27 12  9 27]
  [92 19 94 84]]

 [[14 46 72 20]
  [46 45 17 29]
  [91 50 75 38]]]

Array A2:
[[[93 40 89 21]
  [50 46  8 70]
  [92  5 57 27]]

 [[37 81 99 73]
  [84 93 97 56]
  [14 57 37  3]]]

Joined Array (divisible by 5 from A1 and divisible by 4 from A2):
[90 20 45 50 75 40  8 92 84 56]

Largest Possible Square Matrix:
[[90 20 45]
 [50 75 40]
 [ 8 92 84]]


###
**Question 3:**  Define a function Create_Array () that can create an array of flexible size according to the number of arguments passed within the function call. The elements passed in the function should make the diagonal Elements of the array and the rest of the elements can be all zeros
For Example, if the function call is Create_Array(1,2,3,4)  
The function shall return  
 1 0 0 0  
 0 2 0 0  
 0 0 3 0  
 0 0 0 4  


In [4]:
import numpy as np

# Function to create the diagonal array
def Create_Array(*args):
    # Get the number of arguments (size of the array)
    size = len(args)
    
    # Create an array of zeros with the given size
    array = np.zeros((size, size), dtype=int)
    
    # Assign the passed arguments to the diagonal
    np.fill_diagonal(array, args)
    
    return array

# Example usage
result_array = Create_Array(1, 2, 3, 4)
print("Diagonal Array:")
print(result_array)


Diagonal Array:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
